# Using a specific node version based on Debian Bullseye
FROM node:20.13-bullseye

# Setting an environment variable to minimize issues with automated frontend interactions during package installations
ENV DEBIAN_FRONTEND=noninteractive

# Updating package lists and installing packages in one step to keep the Docker image clean and compact
RUN apt-get update && apt-get install -y \
    vim \
    wget \
    netcat

# Install PM2 globally using npm
RUN npm install pm2 -g

# Create a directory to hold the application code inside the image
RUN mkdir -p /var/www/order_management_server

# Copy the current directory contents into the container at /var/www/order_management_server
COPY . /var/www/order_management_server/

# Set the working directory to /var/www/order_management_server
WORKDIR /var/www/order_management_server

RUN chmod +x ./docker/script/entrypoint.sh
	    
# # Setting the entrypoint to run your script
CMD ["./docker/script/entrypoint.sh"]
